apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: {{ include "<CHARTNAME>.fullname" . }}
    labels:
        {{- include "<CHARTNAME>.labels" . | nindent 4 }}
    {{- with .Values.ingress.annotations }}
    annotations:
        {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
    {{- if .Values.ingress.ingressClassName }}
    ingressClassName: {{ .Values.ingress.ingressClassName }}
    {{- end }}
    {{- if .Values.ingress.tls }}
    tls:
        {{- toYaml .Values.ingress.tls | nindent 4 }}
    {{- end }}
    rules:
        {{- range .Values.ingress.hosts }}
        - host: {{ .host }}
            http:
                paths:
                    {{- range .paths }}
                    - path: {{ .path }}
                        pathType: {{ .pathType | default "Prefix" }}
                        backend:
                            service:
                                name: {{ .service.name }}
                                port:
                                    number: {{ .service.port }}
                    {{- end }}
        {{- end }}